/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export type CaseStatus = (typeof CaseStatus)[keyof typeof CaseStatus];

export const CaseStatus = {
  open: "open",
  in_progress: "in_progress",
  resolved: "resolved",
} as const;

export type CaseCategory = (typeof CaseCategory)[keyof typeof CaseCategory];

export const CaseCategory = {
  repairs: "repairs",
  deposit: "deposit",
  eviction: "eviction",
  noise: "noise",
  harassment: "harassment",
  other: "other",
} as const;

export interface Case {
  id: number;
  title: string;
  description: string;
  state: string;
  status: CaseStatus;
  category: CaseCategory;
  /** @nullable */
  landlordName: string | null;
  /** @nullable */
  landlordEmail: string | null;
  /** @nullable */
  landlordAddress: string | null;
  propertyAddress: string;
  letterCount: number;
  createdAt: string;
  updatedAt: string;
}

export type CreateCaseBodyCategory =
  (typeof CreateCaseBodyCategory)[keyof typeof CreateCaseBodyCategory];

export const CreateCaseBodyCategory = {
  repairs: "repairs",
  deposit: "deposit",
  eviction: "eviction",
  noise: "noise",
  harassment: "harassment",
  other: "other",
} as const;

export interface CreateCaseBody {
  title: string;
  description: string;
  state: string;
  category: CreateCaseBodyCategory;
  landlordName?: string;
  landlordEmail?: string;
  landlordAddress?: string;
  propertyAddress: string;
}

export type UpdateCaseBodyStatus =
  (typeof UpdateCaseBodyStatus)[keyof typeof UpdateCaseBodyStatus];

export const UpdateCaseBodyStatus = {
  open: "open",
  in_progress: "in_progress",
  resolved: "resolved",
} as const;

export type UpdateCaseBodyCategory =
  (typeof UpdateCaseBodyCategory)[keyof typeof UpdateCaseBodyCategory];

export const UpdateCaseBodyCategory = {
  repairs: "repairs",
  deposit: "deposit",
  eviction: "eviction",
  noise: "noise",
  harassment: "harassment",
  other: "other",
} as const;

export interface UpdateCaseBody {
  title?: string;
  description?: string;
  state?: string;
  status?: UpdateCaseBodyStatus;
  category?: UpdateCaseBodyCategory;
  landlordName?: string;
  landlordEmail?: string;
  landlordAddress?: string;
  propertyAddress?: string;
}

export type LetterLetterType =
  (typeof LetterLetterType)[keyof typeof LetterLetterType];

export const LetterLetterType = {
  demand: "demand",
  notice: "notice",
  complaint: "complaint",
  appeal: "appeal",
} as const;

export type LetterTone = (typeof LetterTone)[keyof typeof LetterTone];

export const LetterTone = {
  formal: "formal",
  firm: "firm",
  urgent: "urgent",
} as const;

export interface Letter {
  id: number;
  caseId: number;
  content: string;
  letterType: LetterLetterType;
  tone: LetterTone;
  createdAt: string;
}

export type GenerateLetterBodyLetterType =
  (typeof GenerateLetterBodyLetterType)[keyof typeof GenerateLetterBodyLetterType];

export const GenerateLetterBodyLetterType = {
  demand: "demand",
  notice: "notice",
  complaint: "complaint",
  appeal: "appeal",
} as const;

export type GenerateLetterBodyTone =
  (typeof GenerateLetterBodyTone)[keyof typeof GenerateLetterBodyTone];

export const GenerateLetterBodyTone = {
  formal: "formal",
  firm: "firm",
  urgent: "urgent",
} as const;

export interface GenerateLetterBody {
  letterType: GenerateLetterBodyLetterType;
  tone: GenerateLetterBodyTone;
  additionalContext?: string;
}

export interface CategoryCount {
  category: string;
  count: number;
}

export type ActivityItemType =
  (typeof ActivityItemType)[keyof typeof ActivityItemType];

export const ActivityItemType = {
  case_created: "case_created",
  case_updated: "case_updated",
  letter_generated: "letter_generated",
} as const;

export interface ActivityItem {
  type: ActivityItemType;
  description: string;
  caseId: number;
  caseTitle: string;
  createdAt: string;
}

export interface DashboardSummary {
  totalCases: number;
  openCases: number;
  inProgressCases: number;
  resolvedCases: number;
  totalLetters: number;
  casesByCategory: CategoryCount[];
  recentActivity: ActivityItem[];
}

export type ListCasesParams = {
  status?: ListCasesStatus;
  category?: ListCasesCategory;
};

export type ListCasesStatus =
  (typeof ListCasesStatus)[keyof typeof ListCasesStatus];

export const ListCasesStatus = {
  open: "open",
  in_progress: "in_progress",
  resolved: "resolved",
} as const;

export type ListCasesCategory =
  (typeof ListCasesCategory)[keyof typeof ListCasesCategory];

export const ListCasesCategory = {
  repairs: "repairs",
  deposit: "deposit",
  eviction: "eviction",
  noise: "noise",
  harassment: "harassment",
  other: "other",
} as const;
