/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface ErrorResponse {
    error: string;
}
export type CaseStatus = (typeof CaseStatus)[keyof typeof CaseStatus];
export declare const CaseStatus: {
    readonly open: "open";
    readonly in_progress: "in_progress";
    readonly resolved: "resolved";
};
export type CaseCategory = (typeof CaseCategory)[keyof typeof CaseCategory];
export declare const CaseCategory: {
    readonly repairs: "repairs";
    readonly deposit: "deposit";
    readonly eviction: "eviction";
    readonly noise: "noise";
    readonly harassment: "harassment";
    readonly other: "other";
};
export interface Case {
    id: number;
    title: string;
    description: string;
    state: string;
    status: CaseStatus;
    category: CaseCategory;
    /** @nullable */
    landlordName: string | null;
    /** @nullable */
    landlordEmail: string | null;
    /** @nullable */
    landlordAddress: string | null;
    propertyAddress: string;
    letterCount: number;
    createdAt: string;
    updatedAt: string;
}
export type CreateCaseBodyCategory = (typeof CreateCaseBodyCategory)[keyof typeof CreateCaseBodyCategory];
export declare const CreateCaseBodyCategory: {
    readonly repairs: "repairs";
    readonly deposit: "deposit";
    readonly eviction: "eviction";
    readonly noise: "noise";
    readonly harassment: "harassment";
    readonly other: "other";
};
export interface CreateCaseBody {
    title: string;
    description: string;
    state: string;
    category: CreateCaseBodyCategory;
    landlordName?: string;
    landlordEmail?: string;
    landlordAddress?: string;
    propertyAddress: string;
}
export type UpdateCaseBodyStatus = (typeof UpdateCaseBodyStatus)[keyof typeof UpdateCaseBodyStatus];
export declare const UpdateCaseBodyStatus: {
    readonly open: "open";
    readonly in_progress: "in_progress";
    readonly resolved: "resolved";
};
export type UpdateCaseBodyCategory = (typeof UpdateCaseBodyCategory)[keyof typeof UpdateCaseBodyCategory];
export declare const UpdateCaseBodyCategory: {
    readonly repairs: "repairs";
    readonly deposit: "deposit";
    readonly eviction: "eviction";
    readonly noise: "noise";
    readonly harassment: "harassment";
    readonly other: "other";
};
export interface UpdateCaseBody {
    title?: string;
    description?: string;
    state?: string;
    status?: UpdateCaseBodyStatus;
    category?: UpdateCaseBodyCategory;
    landlordName?: string;
    landlordEmail?: string;
    landlordAddress?: string;
    propertyAddress?: string;
}
export type LetterLetterType = (typeof LetterLetterType)[keyof typeof LetterLetterType];
export declare const LetterLetterType: {
    readonly demand: "demand";
    readonly notice: "notice";
    readonly complaint: "complaint";
    readonly appeal: "appeal";
};
export type LetterTone = (typeof LetterTone)[keyof typeof LetterTone];
export declare const LetterTone: {
    readonly formal: "formal";
    readonly firm: "firm";
    readonly urgent: "urgent";
};
export interface Letter {
    id: number;
    caseId: number;
    content: string;
    letterType: LetterLetterType;
    tone: LetterTone;
    createdAt: string;
}
export type GenerateLetterBodyLetterType = (typeof GenerateLetterBodyLetterType)[keyof typeof GenerateLetterBodyLetterType];
export declare const GenerateLetterBodyLetterType: {
    readonly demand: "demand";
    readonly notice: "notice";
    readonly complaint: "complaint";
    readonly appeal: "appeal";
};
export type GenerateLetterBodyTone = (typeof GenerateLetterBodyTone)[keyof typeof GenerateLetterBodyTone];
export declare const GenerateLetterBodyTone: {
    readonly formal: "formal";
    readonly firm: "firm";
    readonly urgent: "urgent";
};
export interface GenerateLetterBody {
    letterType: GenerateLetterBodyLetterType;
    tone: GenerateLetterBodyTone;
    additionalContext?: string;
}
export interface CategoryCount {
    category: string;
    count: number;
}
export type ActivityItemType = (typeof ActivityItemType)[keyof typeof ActivityItemType];
export declare const ActivityItemType: {
    readonly case_created: "case_created";
    readonly case_updated: "case_updated";
    readonly letter_generated: "letter_generated";
};
export interface ActivityItem {
    type: ActivityItemType;
    description: string;
    caseId: number;
    caseTitle: string;
    createdAt: string;
}
export interface DashboardSummary {
    totalCases: number;
    openCases: number;
    inProgressCases: number;
    resolvedCases: number;
    totalLetters: number;
    casesByCategory: CategoryCount[];
    recentActivity: ActivityItem[];
}
export interface UploadUrlRequest {
    /** @minLength 1 */
    name: string;
    /** @minimum 1 */
    size: number;
    /** @minLength 1 */
    contentType: string;
}
export interface UploadUrlResponse {
    uploadURL: string;
    objectPath: string;
    metadata?: UploadUrlRequest;
}
export type ListCasesParams = {
    status?: ListCasesStatus;
    category?: ListCasesCategory;
};
export type ListCasesStatus = (typeof ListCasesStatus)[keyof typeof ListCasesStatus];
export declare const ListCasesStatus: {
    readonly open: "open";
    readonly in_progress: "in_progress";
    readonly resolved: "resolved";
};
export type ListCasesCategory = (typeof ListCasesCategory)[keyof typeof ListCasesCategory];
export declare const ListCasesCategory: {
    readonly repairs: "repairs";
    readonly deposit: "deposit";
    readonly eviction: "eviction";
    readonly noise: "noise";
    readonly harassment: "harassment";
    readonly other: "other";
};
//# sourceMappingURL=api.schemas.d.ts.map