/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all tenant cases
 */
export const ListCasesQueryParams = zod.object({
  status: zod.enum(["open", "in_progress", "resolved"]).optional(),
  category: zod
    .enum(["repairs", "deposit", "eviction", "noise", "harassment", "other"])
    .optional(),
});

export const ListCasesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  state: zod.string(),
  status: zod.enum(["open", "in_progress", "resolved"]),
  category: zod.enum([
    "repairs",
    "deposit",
    "eviction",
    "noise",
    "harassment",
    "other",
  ]),
  landlordName: zod.string().nullable(),
  landlordEmail: zod.string().nullable(),
  landlordAddress: zod.string().nullable(),
  propertyAddress: zod.string(),
  letterCount: zod.number(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const ListCasesResponse = zod.array(ListCasesResponseItem);

/**
 * @summary Create a new tenant case
 */
export const CreateCaseBody = zod.object({
  title: zod.string(),
  description: zod.string(),
  state: zod.string(),
  category: zod.enum([
    "repairs",
    "deposit",
    "eviction",
    "noise",
    "harassment",
    "other",
  ]),
  landlordName: zod.string().optional(),
  landlordEmail: zod.string().optional(),
  landlordAddress: zod.string().optional(),
  propertyAddress: zod.string(),
});

/**
 * @summary Get recently updated cases
 */
export const GetRecentCasesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  state: zod.string(),
  status: zod.enum(["open", "in_progress", "resolved"]),
  category: zod.enum([
    "repairs",
    "deposit",
    "eviction",
    "noise",
    "harassment",
    "other",
  ]),
  landlordName: zod.string().nullable(),
  landlordEmail: zod.string().nullable(),
  landlordAddress: zod.string().nullable(),
  propertyAddress: zod.string(),
  letterCount: zod.number(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});
export const GetRecentCasesResponse = zod.array(GetRecentCasesResponseItem);

/**
 * @summary Get a specific case
 */
export const GetCaseParams = zod.object({
  id: zod.coerce.number(),
});

export const GetCaseResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  state: zod.string(),
  status: zod.enum(["open", "in_progress", "resolved"]),
  category: zod.enum([
    "repairs",
    "deposit",
    "eviction",
    "noise",
    "harassment",
    "other",
  ]),
  landlordName: zod.string().nullable(),
  landlordEmail: zod.string().nullable(),
  landlordAddress: zod.string().nullable(),
  propertyAddress: zod.string(),
  letterCount: zod.number(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Update a case
 */
export const UpdateCaseParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateCaseBody = zod.object({
  title: zod.string().optional(),
  description: zod.string().optional(),
  state: zod.string().optional(),
  status: zod.enum(["open", "in_progress", "resolved"]).optional(),
  category: zod
    .enum(["repairs", "deposit", "eviction", "noise", "harassment", "other"])
    .optional(),
  landlordName: zod.string().optional(),
  landlordEmail: zod.string().optional(),
  landlordAddress: zod.string().optional(),
  propertyAddress: zod.string().optional(),
});

export const UpdateCaseResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  state: zod.string(),
  status: zod.enum(["open", "in_progress", "resolved"]),
  category: zod.enum([
    "repairs",
    "deposit",
    "eviction",
    "noise",
    "harassment",
    "other",
  ]),
  landlordName: zod.string().nullable(),
  landlordEmail: zod.string().nullable(),
  landlordAddress: zod.string().nullable(),
  propertyAddress: zod.string(),
  letterCount: zod.number(),
  createdAt: zod.coerce.date(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Delete a case
 */
export const DeleteCaseParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List letters for a specific case
 */
export const ListLettersByCaseParams = zod.object({
  id: zod.coerce.number(),
});

export const ListLettersByCaseResponseItem = zod.object({
  id: zod.number(),
  caseId: zod.number(),
  content: zod.string(),
  letterType: zod.enum(["demand", "notice", "complaint", "appeal"]),
  tone: zod.enum(["formal", "firm", "urgent"]),
  createdAt: zod.coerce.date(),
});
export const ListLettersByCaseResponse = zod.array(
  ListLettersByCaseResponseItem,
);

/**
 * @summary Generate a demand letter for a case
 */
export const GenerateLetterParams = zod.object({
  id: zod.coerce.number(),
});

export const GenerateLetterBody = zod.object({
  letterType: zod.enum(["demand", "notice", "complaint", "appeal"]),
  tone: zod.enum(["formal", "firm", "urgent"]),
  additionalContext: zod.string().optional(),
});

/**
 * @summary List all generated letters
 */
export const ListLettersResponseItem = zod.object({
  id: zod.number(),
  caseId: zod.number(),
  content: zod.string(),
  letterType: zod.enum(["demand", "notice", "complaint", "appeal"]),
  tone: zod.enum(["formal", "firm", "urgent"]),
  createdAt: zod.coerce.date(),
});
export const ListLettersResponse = zod.array(ListLettersResponseItem);

/**
 * @summary Get a specific letter
 */
export const GetLetterParams = zod.object({
  id: zod.coerce.number(),
});

export const GetLetterResponse = zod.object({
  id: zod.number(),
  caseId: zod.number(),
  content: zod.string(),
  letterType: zod.enum(["demand", "notice", "complaint", "appeal"]),
  tone: zod.enum(["formal", "firm", "urgent"]),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a letter
 */
export const DeleteLetterParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Get dashboard summary statistics
 */
export const GetDashboardSummaryResponse = zod.object({
  totalCases: zod.number(),
  openCases: zod.number(),
  inProgressCases: zod.number(),
  resolvedCases: zod.number(),
  totalLetters: zod.number(),
  casesByCategory: zod.array(
    zod.object({
      category: zod.string(),
      count: zod.number(),
    }),
  ),
  recentActivity: zod.array(
    zod.object({
      type: zod.enum(["case_created", "case_updated", "letter_generated"]),
      description: zod.string(),
      caseId: zod.number(),
      caseTitle: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
});
