/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
import type { CaseCategory } from "./caseCategory";
import type { CaseStatus } from "./caseStatus";

export interface Case {
  id: number;
  title: string;
  description: string;
  state: string;
  status: CaseStatus;
  category: CaseCategory;
  /** @nullable */
  landlordName: string | null;
  /** @nullable */
  landlordEmail: string | null;
  /** @nullable */
  landlordAddress: string | null;
  propertyAddress: string;
  letterCount: number;
  createdAt: Date;
  updatedAt: Date;
}
