/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
import type { CreateCaseBodyCategory } from "./createCaseBodyCategory";

export interface CreateCaseBody {
  title: string;
  description: string;
  state: string;
  category: CreateCaseBodyCategory;
  landlordName?: string;
  landlordEmail?: string;
  landlordAddress?: string;
  propertyAddress: string;
}
