/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityItem } from "./activityItem";
import type { CategoryCount } from "./categoryCount";

export interface DashboardSummary {
  totalCases: number;
  openCases: number;
  inProgressCases: number;
  resolvedCases: number;
  totalLetters: number;
  casesByCategory: CategoryCount[];
  recentActivity: ActivityItem[];
}
