/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */

export type GenerateLetterBodyTone =
  (typeof GenerateLetterBodyTone)[keyof typeof GenerateLetterBodyTone];

export const GenerateLetterBodyTone = {
  formal: "formal",
  firm: "firm",
  urgent: "urgent",
} as const;
