/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
import type { GenerateLetterBodyLetterType } from "./generateLetterBodyLetterType";
import type { GenerateLetterBodyTone } from "./generateLetterBodyTone";

export interface GenerateLetterBody {
  letterType: GenerateLetterBodyLetterType;
  tone: GenerateLetterBodyTone;
  additionalContext?: string;
}
