/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */

export type LetterLetterType =
  (typeof LetterLetterType)[keyof typeof LetterLetterType];

export const LetterLetterType = {
  demand: "demand",
  notice: "notice",
  complaint: "complaint",
  appeal: "appeal",
} as const;
