/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */

export type LetterTone = (typeof LetterTone)[keyof typeof LetterTone];

export const LetterTone = {
  formal: "formal",
  firm: "firm",
  urgent: "urgent",
} as const;
