/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateCaseBodyCategory } from "./updateCaseBodyCategory";
import type { UpdateCaseBodyStatus } from "./updateCaseBodyStatus";

export interface UpdateCaseBody {
  title?: string;
  description?: string;
  state?: string;
  status?: UpdateCaseBodyStatus;
  category?: UpdateCaseBodyCategory;
  landlordName?: string;
  landlordEmail?: string;
  landlordAddress?: string;
  propertyAddress?: string;
}
