/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * TenantShield API specification
 * OpenAPI spec version: 0.1.0
 */

export type UpdateCaseBodyCategory =
  (typeof UpdateCaseBodyCategory)[keyof typeof UpdateCaseBodyCategory];

export const UpdateCaseBodyCategory = {
  repairs: "repairs",
  deposit: "deposit",
  eviction: "eviction",
  noise: "noise",
  harassment: "harassment",
  other: "other",
} as const;
